from __future__ import absolute_import

import os
import shutil
import sys

import pytest


def main():
    exit_code = pytest.main()

    save_coverage_report()

    # TODO when upgrading to pytest >= 5.0.0 use `pytest.ExitCode`
    # http://doc.pytest.org/en/latest/reference.html#pytest-exitcode

    # Suppress exit code 5, which means no tests were collected, in case all
    # tests need to be skipped due to the platform or other support limitations
    # https://docs.pytest.org/en/latest/usage.html#possible-exit-codes
    if exit_code != 5:
        sys.exit(exit_code)


def save_coverage_report():
    """
    Save the coverage report generated by coverage.py run as part of pytest-cov.
    """
    src = ".coverage"
    if not os.path.exists(src):
        return

    try:
        # See the following two links for more about interacting with `TEST_UNDECLARED_OUTPUTS_DIR`.
        # https://stackoverflow.com/questions/47871993/bazel-writable-archivable-path-for-test-runtime
        # https://docs.bazel.build/versions/master/test-encyclopedia.html#test-interaction-with-the-filesystem
        dest = os.environ["TEST_UNDECLARED_OUTPUTS_DIR"]
    except KeyError:
        return
    else:
        dest = os.path.join(dest, ".coverage")
        shutil.move(src, dest)


if __name__ == "__main__":
    main()
